name: MLflow-CI-Retraining

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  retrain-and-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow dagshub scikit-learn pandas numpy joblib matplotlib setuptools

      - name: Run MLflow Project (Official Retraining)
        run: |
          # Perintah resmi sesuai kriteria penguji
          mlflow run MLProject/ --env-manager local
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
          DAGSHUB_CLIENT_TOKEN: ${{ secrets.MLFLOW_PASSWORD }}

      - name: Build Status Notification
        if: success()
        run: echo "Retraining Berhasil!"