name: MLflow-CI-Training

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-track:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          # Menginstal semua library yang dibutuhkan langsung di environment runner
          pip install mlflow dagshub scikit-learn pandas numpy joblib matplotlib setuptools

      - name: Run MLflow Project
        run: |
          # Menggunakan --env-manager local untuk bypass pembuatan conda env oleh MLflow
          # Ini memperbaiki error "activate: No such file or directory"
          mlflow run MLProject/ -e main --env-manager local
        env:
          # Pastikan Secret ini sudah ada di Settings > Secrets > Actions di GitHub
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_PASSWORD }}
          DAGSHUB_CLIENT_TOKEN: ${{ secrets.MLFLOW_PASSWORD }}

      - name: Build Status Notification
        if: success()
        run: echo "CI Pipeline berhasil dijalankan dan Model telah terdaftar di DagsHub."